
# window
window_padding_width 7

# cursor
cursor_shape block
cursor_blink_interval -1

vim:ft=kitty

#: basic colors

foreground              #fde8e7
background              #171617
selection_background    #fde8e7
selection_foreground    #2a2522

# cursor colors
cursor                  #f5E0dc
cursor_text_color       #1e1e2e

# URL underline color when hovering with mouse
url_color               #f5e0dc

#: OS window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system


# colors for marks (marked text in the terminal)

mark1_foreground #1e1e2e
mark1_background #96cdfb
mark2_foreground #1e1e2e
mark2_background #f5c2e7
mark3_foreground #1e1e2e
mark3_background #b5e8e0

#: terminal colors

#: black
color0 #6e6c7e
color8 #988ba2

#: red 
color1 #d34f80
color9 #d34f80

#: green
color2  #a6e3a1
color10 #a6e3a1

#: yellow
color3  #f9e2af
color11 #f9e2af

#: blue
color4  #74c7ec
color12 #74c7ec

#: magenta 
color5  #e68ae2
color13 #e68ae2

#: cyan
color6  #89dceb
color14 #89dceb

#: white 
color7  #fde8e7
color15 #fde8e7

#: fonts
font_family Source Code Pro Bold
font_size 12.7
