# ~/.config/starship.toml

format = """
[](#EB82AB)\
$username\
[](bg:#171617  fg:#EB82AB)\
$directory\
[](bg:#171617 fg:#FAD8D7)\
$git_branch\
[ ](fg:#FAD8D7)\
"""

[username]
show_always = true
style_user = "#171617 bg:#EB82AB"
style_root = "#171617 bg:#EB82AB"
format = '[>]($style)'

[directory]
style = "fg:#FDE8E7 bg:#171617"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = ""

[git_branch]
symbol = ""
style = "#1c1917 bg:#FAD8D7"
format = '[[ $symbol $branch ](#171617 bg:#FAD8D7)]($style)'

[git_status]
style = "#1c1917 bg:#FAD8D7"
format = '[[($all_status$ahead_behind )](#171617 bg:#FAD8D7)]($style)'

# check current directory files time
scan_timeout = 10

# din bug message in terminal
add_newline = false

