#!/bin/bash
bat_files="/sys/class/power_supply/BAT0"
bat_status=$(cat "${bat_files}/status")
capacity=$(cat "${bat_files}/capacity")
echo "${capacity}"
if [[ "${bat_status}"=="Discharging" && ${capacity} -le 10 ]]; then
	echo "battery alert - ${capacity}%"
	notify-send \
		"low battery" \
		"only ${capacity}$ battery remaining"
fi
